apiVersion: v2.edp.epam.com/v1
kind: GerritProjectAccess
metadata:
  name: test-access1
spec:
  projectName: test123
  references:
    - refPattern: "refs/for/*"
      permissionName: "label-Verified"
      groupName: "Administrators"
      action: "ALLOW"
      min: -1
      max: 1
    - refPattern: "refs/for/*"
      permissionName: "label-Verified"
      groupName: "test321"
      action: "ALLOW"
      min: -1
      max: 1
