apiVersion: v1.edp.epam.com/v1
kind: GerritGroupMember
metadata:
  labels:
    app.kubernetes.io/name: gerritgroupmember
    app.kubernetes.io/instance: gerritgroupmember-sample
    app.kubernetes.io/part-of: empty-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: empty-operator
  name: gerritgroupmember-sample
spec:
  # TODO(user): Add fields here
