apiVersion: v1.edp.epam.com/v1
kind: GerritGroup
metadata:
  labels:
    app.kubernetes.io/name: gerritgroup
    app.kubernetes.io/instance: gerritgroup-sample
    app.kubernetes.io/part-of: empty-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: empty-operator
  name: gerritgroup-sample
spec:
  # TODO(user): Add fields here
