global:
  edpName: ""
  platform: "openshift"
  dnsWildCard: "eks-delivery.aws.main.edp.projects.epam.com"
  admins:
    - "stub_user_one@example.com"
  openshift:
    deploymentType: "deploymentConfigs"

name: gerrit-operator
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
image:
  name: epamedp/gerrit-operator
  # if not defined then .Chart.AppVersion is used
  version:
imagePullPolicy: "IfNotPresent"

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

gerrit:
  deploy: true
  name: "gerrit"
  image: "openfrontier/gerrit"
  sshPort: "30022"
  port: "8080"
  version: "3.3.2"
  imagePullPolicy: "IfNotPresent"
  imagePullSecrets:
  storage:
    size: 1Gi
    class: gp2
  basePath: ""
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ingress:
    annotations: {}
    # pathType is only for k8s >= 1.1=
    pathType: Prefix
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    # ingressClassName: nginx

  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi

gitServer:
  name: "gerrit"
  user: "jenkins"
  httpsPort: 443
  nameSshKeySecret: "gerrit-ciuser-sshkey"
