global:
  edpName: ""
  platform: "kubernetes"
  dnsWildCard: "eks-delivery.aws.main.edp.projects.epam.com"
  admins:
    - "stub_user_one@example.com"

name: gerrit-operator
image:
  name: epamedp/gerrit-operator
  version: v2.5.0

resources:
  limits:
    cpu: 200m
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

gerrit:
  deploy: true
  name: "gerrit"
  image: "openfrontier/gerrit"
  sshPort: "30022"
  port: "8080"
  version: "3.2.5.1"
  imagePullSecrets:
  storage:
    size: 1Gi
    class: gp2
  basePath: ""

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi

gitServer:
  name: "gerrit"
  user: "jenkins"
  httpsPort: 443
  nameSshKeySecret: "gerrit-ciuser-sshkey"
