global:
  edpName: ""
  platform: "openshift"
  dnsWildCard: "example.com"
  admins:
    - "stub_user_one@example.com"
  developers:
    - "stub_user_one@example.com"
    - "stub_user_two@example.com"
  openshift:
    deploymentType: "deployments"

name: gerrit-operator
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
image:
  name: epamedp/gerrit-operator
  # -- if not defined then .Chart.AppVersion is used
  version:
imagePullPolicy: "IfNotPresent"

# Define interval for synchronizing Gerrit Projects with GerritProject CustomResources
# Default: 5 minutes
# Format: golang time.Duration-formatted string
projectSyncInterval: 1h

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

gerrit:
  deploy: true
  name: "gerrit"
  # -- Define gerrit docker image name
  image: "epamedp/edp-gerrit"
  # -- Define gerrit docker image tag
  version: "3.6.1-SNAPSHOT.2"
  # -- If defined, a imagePullPolicy applied for gerrit deployment
  imagePullPolicy: "IfNotPresent"
  imagePullSecrets:
  sshPort: "30022"
  port: "8080"
  storage:
    size: 1Gi
    class: gp2
  basePath: ""
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ingress:
    annotations: {}
    # pathType is only for k8s >= 1.1=
    pathType: Prefix
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    # ingressClassName: nginx
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi

gitServer:
  name: "gerrit"
  user: "jenkins"
  httpsPort: 443
  nameSshKeySecret: "gerrit-ciuser-sshkey"
