{{- if .Values.gerrit.deploy -}}
apiVersion: v2.edp.epam.com/v1alpha1
kind: GerritGroup
metadata:
  name: developers
spec:
  name: Developers
  description: Grant access to all projects in Gerrit
  visibleToAll: false
{{end}}