{{- if .Values.gerrit.deploy -}}
{{- range .Values.global.developers }}
apiVersion: v2.edp.epam.com/v1alpha1
kind: GerritGroupMember
metadata:
  name: {{ regexReplaceAll "@.*" . "" | replace "_" "-" }}-developers
spec:
  groupId: Developers
  accountId: {{ . }}
---
{{end}}
{{end}}