apiVersion: v2.edp.epam.com/v1alpha1
kind: GitServer
metadata:
  name: {{.Values.gitServer.name}}
spec:
  createCodeReviewPipeline: false
  edpSpec:
    dnsWildcard: {{ .Values.edp.dnsWildCard }}
  gitHost: 'gerrit.{{ .Values.namespace }}'
  gitUser: {{.Values.gitServer.user}}
  httpsPort: {{.Values.gitServer.httpsPort}}
  nameSshKeySecret: {{.Values.gitServer.nameSshKeySecret}}
  sshPort: {{.Values.gitServer.sshPort}}