# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/v1.edp.epam.com_gerrits.yaml
- bases/v1.edp.epam.com_gerritgroups.yaml
- bases/v1.edp.epam.com_gerritgroupmembers.yaml
- bases/v1.edp.epam.com_gerritmergerequests.yaml
- bases/v1.edp.epam.com_gerritprojects.yaml
- bases/v1.edp.epam.com_gerritprojectaccesses.yaml
- bases/v1.edp.epam.com_gerritreplicationconfigs.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_gerrits.yaml
#- patches/webhook_in_gerritgroups.yaml
#- patches/webhook_in_gerritgroupmembers.yaml
#- patches/webhook_in_gerritmergerequests.yaml
#- patches/webhook_in_gerritprojects.yaml
#- patches/webhook_in_gerritprojectaccesses.yaml
#- patches/webhook_in_gerritreplicationconfigs.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_gerrits.yaml
#- patches/cainjection_in_gerritgroups.yaml
#- patches/cainjection_in_gerritgroupmembers.yaml
#- patches/cainjection_in_gerritmergerequests.yaml
#- patches/cainjection_in_gerritprojects.yaml
#- patches/cainjection_in_gerritprojectaccesses.yaml
#- patches/cainjection_in_gerritreplicationconfigs.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
