{{ if eq .Values.global.platform "kubernetes" }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.gerrit.name }}
  labels:
    app: {{ .Values.gerrit.name }}
    {{- include "gerrit-operator.labels" . | nindent 4 }}
  {{- with .Values.gerrit.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{if .Values.gerrit.basePath}}{{ .Values.global.dnsWildCard }}{{else}}gerrit-{{ .Values.global.edpName }}.{{ .Values.global.dnsWildCard }}{{end}}
      http:
        paths:
          - path: {{if .Values.gerrit.basePath}}/{{.Values.gerrit.basePath}}(/|$)(.*){{else}}/{{end}}
            backend:
              serviceName: {{ .Values.gerrit.name }}
              servicePort: 8080
status:
  loadBalancer:
    ingress:
{{ end }}