{{- if eq .Values.global.platform "openshift" -}}
{{- if .Values.gerrit.deploy -}}
allowHostDirVolumePlugin: false
allowHostIPC: true
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: []
allowedFlexVolumes: []
apiVersion: security.openshift.io/v1
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
groups: []
kind: SecurityContextConstraints
metadata:
  labels:
    app: {{.Values.gerrit.name}}
    {{- include "gerrit-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
  name: {{.Values.gerrit.name}}-{{.Release.Namespace}}
priority: 1
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: MustRunAs
  uid: 0
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:{{.Release.Namespace}}:{{.Values.gerrit.name}}
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
{{- end -}}
{{- end -}}