{{- if .Values.gerrit.deploy -}}
apiVersion: v1
data:
  sshPort: "{{.Values.gerrit.sshPort}}"
kind: ConfigMap
metadata:
  labels:
    {{- include "gerrit-operator.labels" . | nindent 4 }}
  name: {{.Values.gerrit.name}}
{{end}}
